routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');
Route::resource('department', 'DepartmentController');

app/Department.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Department extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'description', 'logo',
    ];

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_departments');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/UserDepartment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class UserDepartment extends Model
{
    protected $fillable = ['user_id', 'department_id'];

}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DepartmentController.php
<?php

namespace App\Http\Controllers;

use App\Department;
use App\Http\Requests\DepartmentRequest;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Arr;

class DepartmentController extends Controller
{
    public function __construct(Department $department, User $user)
    {
        $this->department = $department;
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = $this->department->latest()->paginate(10);
        return view('department.index', compact('departments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = $this->user->all();
        return view('department.create', compact('users'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(DepartmentRequest $request)
    {
        $data = $request->all();
        $data['logo'] = $request->file('logo')->store('logo');
        $department = $this->department::create($data);
        $department->users()->sync($request->users);

        return redirect()->route('department.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!$department = $this->department->find($id))
            return redirect()->back();

        return view('department.show', compact('department'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!$department = $this->department->find($id))
            return redirect()->back();
        $users = $this->user->all();

        $selected_users = Arr::pluck($department->users()->get()->toArray(), 'id');

        return view('department.edit', [
            'users' => $users,
            'selected_users' => $selected_users,
            'department' => $department,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(DepartmentRequest $request, $id)
    {
        if (!$department = $this->department->find($id))
            return redirect()->back();

        $department->update($request->all());
        $department->users()->sync($request->users);

        return redirect()->route('department.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!$department = $this->department->find($id))
            return redirect()->back();

        $department->delete();
        return redirect()->route('department.index');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserRequest;
use App\User;
use Illuminate\Http\Request;

class UserController extends Controller
{
    public function __construct(User $user)
    {
        $this->user = $user;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = $this->user->latest()->paginate(10);
        return view('user.index', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $this->user->create($request->all());
        return redirect()->route('user.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!$user = $this->user->find($id))
            return redirect()->back();

        return view('user.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        if (!$user = $this->user->find($id))
            return redirect()->back();

        return view('user.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, $id)
    {
        if (!$user = $this->user->find($id))
            return redirect()->back();

        $user->update($request->all());
        return redirect()->route('user.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if (!$user = $this->user->find($id))
            return redirect()->back();

        $user->delete();
        return redirect()->route('user.index');
    }
}

resources/views/department/_partials/form.blade.php
@include('includes.alerts')
@csrf
<div class="form-group">
    <input value="{{ $department->name ?? old('name') }}" class="form-control" type="text" name="name" placeholder="Name">
</div>
<div class="form-group">
    <input value="{{ $department->description ?? old('description') }}" class="form-control" type="text" name="description" placeholder="Description">
</div>
<div class="form-group">
    <label for="logo">Logo</label>
    <input class="form-control" type="file" name="logo">
</div>

resources/views/department/create.blade.php
@extends('layouts.app')
@section('title', 'Create new department')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Create department</h1>
                <form action="{{ route('department.store') }}" method="post" enctype="multipart/form-data">
                    @include('department._partials.form')
                    <div class="form-group">
                        <h2>Users</h2>
                        @foreach($users as $user)
                            <p>
                                <input type="checkbox" value="{{ $user->id }}" name="users[]">
                                <label for="{{ $user->id }}">{{ $user->name }} <a
                                            href="mailto:{{ $user->email }}">{{ $user->email }}</a></label>
                            </p>
                        @endforeach
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/department/edit.blade.php
@extends('layouts.app')
@section('title', "Edit department {$department->id}")
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Edit department {{$department->id}}</h1>
                <form action="{{ route('department.update', $department->id) }}" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="PUT">
                    @include('department._partials.form')
                    <div class="form-group">
                        <h2>Users</h2>
                        @foreach($users as $user)
                            <p>


                                <input type="checkbox" value="{{ $user->id }}" name="users[]" @if(in_array($user->id, $selected_users)) checked @endif>
                                <label for="{{ $user->id }}">{{ $user->name }} <a
                                            href="mailto:{{ $user->email }}">{{ $user->email }}</a></label>
                            </p>
                        @endforeach
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-success">Сохранить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/department/index.blade.php
@extends('layouts.app')
@section('title', 'List departments')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="display-5">Departments</h1>
                <div class="btn-group mb-3">
                    <a class="btn btn-dark" href="{{ route('department.create') }}">Add new department</a>
                </div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>Logo</td>
                        <td>Name</td>
                        <td>Description</td>
                        <td>Users</td>
                        <td colspan=2>Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($departments as $department)
                        <tr>
                            <td><img class="img-responsive" style="max-width: 100px" src="{{ url($department->logo) }}" alt=""></td>
                            <td>{{ $department->name }}</td>
                            <td>{{ $department->description }}</td>
                            <td>
                                <ol>
                                    @foreach ($department->users as $user)
                                        <li>{{ $user->name }}</li>
                                    @endforeach
                                </ol>
                            </td>
                            <td>
                                <a href="{{ route('department.edit',$department->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <form action="{{ route('department.destroy', $department->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $departments->render() }}
            </div>
        </div>
    </div>
@endsection

resources/views/department/show.blade.php
@extends('layouts.app')
@section('title', "Show department {$department->id}")
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Show department {{ $department->id }}</h1>
                <p>Name: {{ $department->name }}</p>
                <p>Email: {{ $department->description }}</p>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/includes/alerts.blade.php
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

@if (session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
@endif

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/_partials/form.blade.php
@include('includes.alerts')
@csrf
<div class="form-group">
    <input value="{{ $user->name ?? old('name') }}" class="form-control" type="text" name="name" placeholder="Name">
</div>
<div class="form-group">
    <input value="{{ $user->email ?? old('email') }}" class="form-control" type="text" name="email" placeholder="Email">
</div>
<div class="form-group">
    <input value="{{ $user->password ?? old('password') }}" class="form-control" type="text" name="password" placeholder="Password">
</div>
<div class="form-group">
    <button type="submit" class="btn btn-success">Сохранить</button>
</div>

resources/views/user/create.blade.php
@extends('layouts.app')
@section('title', 'Create new user')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Create user</h1>
                <form action="{{ route('user.store') }}" method="post" enctype="multipart/form-data">
                    @include('user._partials.form')
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/edit.blade.php
@extends('layouts.app')
@section('title', "Edit user {$user->id}")
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Edit user {{$user->id}}</h1>
                <form action="{{ route('user.update', $user->id) }}" method="post" enctype="multipart/form-data">
                    <input type="hidden" name="_method" value="PUT">
                    @include('user._partials.form')
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/user/index.blade.php
@extends('layouts.app')
@section('title', 'List users')
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1 class="display-5">Users</h1>
                <div class="btn-group mb-3">
                    <a class="btn btn-dark" href="{{ route('user.create') }}">Add new user</a>
                </div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <td>Name</td>
                        <td>Email</td>
                        <td>Created At</td>
                        <td colspan=2>Actions</td>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{$user->name}}</td>
                            <td>{{$user->email}}</td>
                            <td>{{$user->created_at}}</td>
                            <td>
                                <a href="{{ route('user.edit',$user->id)}}" class="btn btn-primary">Edit</a>
                            </td>
                            <td>
                                <form action="{{ route('user.destroy', $user->id)}}" method="post">
                                    @csrf
                                    @method('DELETE')
                                    <button class="btn btn-danger" type="submit">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {{ $users->render() }}
            </div>
        </div>
    </div>
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')
@section('title', "Show user {$user->id}")
@section('content')
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Show user {{ $user->id }}</h1>
                <p>Name: {{ $user->name }}</p>
                <p>Email: {{ $user->email }}</p>
            </div>
        </div>
    </div>
@endsection